// ALBUMS
export const GET_ALBUM_RQ = 'GET_ALBUM_RQ'
export const GET_ALBUM_OK = 'GET_ALBUM_OK'

// SEARCH
export const GET_SEARCH_ALBUMS_RQ = 'GET_SEARCH_ALBUMS_RQ'
export const GET_SEARCH_ALBUMS_OK = 'GET_SEARCH_ALBUMS_OK'
